version: "3.7"
services:
  terraform:
    build: ./
    volumes:
      - "./Terraform:/Terraform"
      - "/${HOME}/.ssh:/root/.ssh"
    environment:
      - SUBSCRIPTION_ID=${SUBSCRIPTION_ID}
      - PATH=/:${PATH}
    tty: true
